onlyBuiltDependencies:
  - '@ffmpeg-installer/darwin-arm64'
  - '@ffmpeg-installer/darwin-x64'
  - '@ffmpeg-installer/linux-arm'
  - '@ffmpeg-installer/linux-arm64'
  - '@ffmpeg-installer/linux-ia32'
  - '@ffmpeg-installer/linux-x64'
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - msgpackr-extract
  - onnxruntime-node
  - protobufjs
  - sharp
  - unrs-resolver
  - vue-demi
